steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-rgl/roguelike-repo/roguelike-service:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-rgl/roguelike-repo/roguelike-service:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'roguelike-service'
  - '--image'
  - 'us-central1-docker.pkg.dev/gcp-rgl/roguelike-repo/roguelike-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'ASSET_BUCKET=malathon-roguelike-asset'
  - '--project'
  - 'gcp-rgl'

# Store images in Google Artifact Registry
images:
- 'us-central1-docker.pkg.dev/gcp-rgl/roguelike-repo/roguelike-service:$COMMIT_SHA'

# Set timeout
timeout: '1600s'

# Add logging options
options:
  logging: CLOUD_LOGGING_ONLY

# Alternatively, you can specify a logs bucket
# logs_bucket: 'gs://malathon-roguelike-asset/build-logs' 